### ISSUE TITLE
For which Raspi type is this new version intended? 4 or 5? I can't set a GPIO in the 4.

### ISSUE THREAD

**Issue by OttiNC1** [iobroker-community-adapters/ioBroker.rpi2#184] opened 2024-05-24 15:18 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by OttiNC1** [comment] 2024-05-25 07:55
I cannot set an output GPIO. About writing in the object.

**Comment by Garfonso** [comment] 2024-05-25 15:18
Is your issue an duplicate of #167?

**Comment by OttiNC1** [comment] 2024-05-26 06:39
Actually, I didn't want to ask a new question. I want to know if the alpha version is for the Raspi 4 or for the 5.

**Comment by Garfonso** [comment] 2024-05-26 19:51
The alpha version is not meant for public, yet. It should not show up as update in iobroker. Right?

Currently functionalilty should be the same as the 1.3.2 version, just with updated infrastructure, so that releases are possible (and I was annoyed by objects that stayed after disabling options, so I repaired that part).

But gpio is still the same. Working for pre bookworm raspian and failing on bookworm. You might want to watch the other issue, I'll sure ask for testers there. Since I don't know much about gpio that will be necessary. 🙄

**Closed** 2024-05-26 19:52 UTC
